import type { RegulatorySourceCatalogEntry } from "./types";

// Production retrieval must be restricted to official government sources.
// Subdomains are permitted only when their registrable parent is listed here.
export const APPROVED_OFFICIAL_DOMAIN_SUFFIXES = [
  "acquisition.gov",
  "ecfr.gov",
  "federalregister.gov",
  "dol.gov",
  "sam.gov",
  "nist.gov",
  "defense.gov",
  "archives.gov",
] as const;

export function isApprovedOfficialHostname(hostname: string): boolean {
  const normalized = hostname.toLowerCase().replace(/^www\./, "");
  return APPROVED_OFFICIAL_DOMAIN_SUFFIXES.some(
    (suffix) => normalized === suffix || normalized.endsWith(`.${suffix}`)
  );
}

export function isApprovedOfficialUrl(url: string): boolean {
  try {
    const parsed = new URL(url);
    return parsed.protocol === "https:" && isApprovedOfficialHostname(parsed.hostname);
  } catch {
    return false;
  }
}

const verifiedAt = "2026-07-25";

export const REGULATORY_SOURCE_CATALOG = [
  {
    sourceId: "far-current",
    sourceFamily: "FAR",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "Federal Acquisition Regulatory Council",
    canonicalTitle: "Federal Acquisition Regulation",
    canonicalUrl: "https://www.acquisition.gov/browse/index/far",
    sourceType: "regulation",
    updateCadence: "event-driven",
    versionStrategy: "Federal Acquisition Circular number and effective date",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes:
      "Primary source for FAR text, prescriptions, clauses, FAC metadata, and archived versions relevant to federal subcontract flowdowns.",
    currentVerifiedVersion: {
      versionIdentifier: "FAC 2026-01",
      effectiveDate: "2026-03-13",
      verifiedAt,
      provenanceUrl: "https://www.acquisition.gov/browse/index/far",
    },
  },
  {
    sourceId: "dfars-current",
    sourceFamily: "DFARS",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "U.S. Department of Defense",
    canonicalTitle: "Defense Federal Acquisition Regulation Supplement",
    canonicalUrl: "https://www.acquisition.gov/dfars",
    sourceType: "regulation",
    updateCadence: "event-driven",
    versionStrategy: "DFARS change number and effective date",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes:
      "Primary source for DoD acquisition regulations, prescriptions, clauses, change metadata, and archived versions.",
    currentVerifiedVersion: {
      versionIdentifier: "DFARS Change 5/7/2026",
      effectiveDate: "2026-05-07",
      verifiedAt,
      provenanceUrl: "https://www.acquisition.gov/dfars",
    },
  },
  {
    sourceId: "ecfr-title-48",
    sourceFamily: "eCFR",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "Office of the Federal Register and U.S. Government Publishing Office",
    canonicalTitle: "eCFR Title 48 — Federal Acquisition Regulations System",
    canonicalUrl: "https://www.ecfr.gov/current/title-48",
    sourceType: "regulation",
    updateCadence: "daily",
    versionStrategy: "eCFR current-through date plus retained retrieval snapshot",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes:
      "Current electronic CFR source for FAR and agency acquisition-regulation chapters; retain Federal Register and Acquisition.gov provenance where controlling version history matters.",
  },
  {
    sourceId: "federal-register-acquisition",
    sourceFamily: "Federal Register",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "Office of the Federal Register",
    canonicalTitle: "Federal Register",
    canonicalUrl: "https://www.federalregister.gov/",
    sourceType: "regulation",
    updateCadence: "daily",
    versionStrategy: "Document number, publication date, rule status, and effective date",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes:
      "Primary provenance for final rules, interim rules, corrections, effective dates, and implementation notices.",
  },
  {
    sourceId: "dol-government-contracts",
    sourceFamily: "DOL",
    sourceTier: "official-guidance",
    jurisdiction: "federal",
    issuingAuthority: "U.S. Department of Labor, Wage and Hour Division",
    canonicalTitle: "Government Contracts Compliance Assistance",
    canonicalUrl: "https://www.dol.gov/agencies/whd/government-contracts",
    sourceType: "guidance",
    updateCadence: "weekly",
    versionStrategy: "Retrieved guidance snapshot with page update metadata when available",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes:
      "Official explanatory guidance for Davis-Bacon, Service Contract Labor Standards, certified payroll, wage determinations, and related labor requirements; does not replace controlling statutes, regulations, or clauses.",
  },
  {
    sourceId: "dol-davis-bacon",
    sourceFamily: "DOL",
    sourceTier: "official-guidance",
    jurisdiction: "federal",
    issuingAuthority: "U.S. Department of Labor, Wage and Hour Division",
    canonicalTitle: "Davis-Bacon and Related Acts",
    canonicalUrl: "https://www.dol.gov/agencies/whd/government-contracts/construction",
    sourceType: "guidance",
    updateCadence: "weekly",
    versionStrategy: "Retrieved guidance snapshot with page update metadata when available",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes:
      "Official Davis-Bacon coverage and compliance guidance, including wage-determination selection and conformance resources.",
  },
  {
    sourceId: "dol-service-contract-labor-standards",
    sourceFamily: "DOL",
    sourceTier: "official-guidance",
    jurisdiction: "federal",
    issuingAuthority: "U.S. Department of Labor, Wage and Hour Division",
    canonicalTitle: "Service Contract Labor Standards Resources",
    canonicalUrl: "https://www.dol.gov/agencies/whd/government-contracts/service-contracts",
    sourceType: "guidance",
    updateCadence: "weekly",
    versionStrategy: "Retrieved guidance snapshot with page update metadata when available",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes:
      "Official guidance for the McNamara-O'Hara Service Contract Act / Service Contract Labor Standards and related wage determinations.",
  },
  {
    sourceId: "sam-wage-determinations",
    sourceFamily: "SAM Wage Determinations",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "U.S. General Services Administration and U.S. Department of Labor",
    canonicalTitle: "SAM.gov Wage Determinations",
    canonicalUrl: "https://sam.gov/content/wage-determinations",
    sourceType: "wage-determination-index",
    updateCadence: "weekly",
    versionStrategy:
      "Determination number, modification number, publication date, location, construction type or service category, classifications, rates, fringe benefits, and active status",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes:
      "Official source for current and archived Davis-Bacon and Service Contract Labor Standards wage determinations. Never infer rates or classifications from a malformed, fictional, or incomplete identifier.",
  },
  {
    sourceId: "ecfr-29-part-1",
    sourceFamily: "eCFR",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "U.S. Department of Labor",
    canonicalTitle: "29 CFR Part 1 — Procedures for Predetermination of Wage Rates",
    canonicalUrl: "https://www.ecfr.gov/current/title-29/subtitle-A/part-1",
    sourceType: "regulation",
    updateCadence: "daily",
    versionStrategy: "eCFR current-through date plus retained retrieval snapshot",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes: "Davis-Bacon wage-determination procedures and incorporation requirements.",
  },
  {
    sourceId: "ecfr-29-part-3",
    sourceFamily: "eCFR",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "U.S. Department of Labor",
    canonicalTitle: "29 CFR Part 3 — Contractors and Subcontractors on Public Building or Public Work",
    canonicalUrl: "https://www.ecfr.gov/current/title-29/subtitle-A/part-3",
    sourceType: "regulation",
    updateCadence: "daily",
    versionStrategy: "eCFR current-through date plus retained retrieval snapshot",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes: "Copeland Act payroll deductions, certified statements, and anti-kickback requirements.",
  },
  {
    sourceId: "ecfr-29-part-4",
    sourceFamily: "eCFR",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "U.S. Department of Labor",
    canonicalTitle: "29 CFR Part 4 — Labor Standards for Federal Service Contracts",
    canonicalUrl: "https://www.ecfr.gov/current/title-29/subtitle-A/part-4",
    sourceType: "regulation",
    updateCadence: "daily",
    versionStrategy: "eCFR current-through date plus retained retrieval snapshot",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes: "Service Contract Labor Standards coverage, exemptions, wage determinations, and employee classifications.",
  },
  {
    sourceId: "ecfr-29-part-5",
    sourceFamily: "eCFR",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "U.S. Department of Labor",
    canonicalTitle: "29 CFR Part 5 — Labor Standards Provisions Applicable to Federal Contracts",
    canonicalUrl: "https://www.ecfr.gov/current/title-29/subtitle-A/part-5",
    sourceType: "regulation",
    updateCadence: "daily",
    versionStrategy: "eCFR current-through date plus retained retrieval snapshot",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes: "Davis-Bacon labor standards, records, certified payroll, conformance, and enforcement requirements.",
  },
  {
    sourceId: "far-52-222-4",
    sourceFamily: "FAR",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "Federal Acquisition Regulatory Council",
    canonicalTitle: "FAR 52.222-4 — Contract Work Hours and Safety Standards—Overtime Compensation",
    canonicalUrl: "https://www.acquisition.gov/far/52.222-4",
    sourceType: "clause",
    updateCadence: "event-driven",
    versionStrategy: "Clause revision date plus governing FAC snapshot",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes: "Construction and labor overtime requirements where the clause is applicable or flowed down.",
  },
  {
    sourceId: "far-52-222-6",
    sourceFamily: "FAR",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "Federal Acquisition Regulatory Council",
    canonicalTitle: "FAR 52.222-6 — Construction Wage Rate Requirements",
    canonicalUrl: "https://www.acquisition.gov/far/52.222-6",
    sourceType: "clause",
    updateCadence: "event-driven",
    versionStrategy: "Clause revision date plus governing FAC snapshot",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes: "Core subcontract-facing Davis-Bacon construction wage clause when applicable.",
  },
  {
    sourceId: "far-52-222-8",
    sourceFamily: "FAR",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "Federal Acquisition Regulatory Council",
    canonicalTitle: "FAR 52.222-8 — Payrolls and Basic Records",
    canonicalUrl: "https://www.acquisition.gov/far/52.222-8",
    sourceType: "clause",
    updateCadence: "event-driven",
    versionStrategy: "Clause revision date plus governing FAC snapshot",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes: "Certified payroll, recordkeeping, worker interview, and lower-tier obligations for covered construction.",
  },
  {
    sourceId: "far-52-222-41",
    sourceFamily: "FAR",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "Federal Acquisition Regulatory Council",
    canonicalTitle: "FAR 52.222-41 — Service Contract Labor Standards",
    canonicalUrl: "https://www.acquisition.gov/far/52.222-41",
    sourceType: "clause",
    updateCadence: "event-driven",
    versionStrategy: "Clause revision date plus governing FAC snapshot",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes: "Core service-employee wage and fringe-benefit clause when applicable to the subcontract.",
  },
  {
    sourceId: "nist-sp-800-171-r3",
    sourceFamily: "NIST",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "National Institute of Standards and Technology",
    canonicalTitle: "NIST SP 800-171 Revision 3 — Protecting CUI in Nonfederal Systems and Organizations",
    canonicalUrl: "https://csrc.nist.gov/Pubs/sp/800/171/r3/final",
    sourceType: "standard",
    updateCadence: "event-driven",
    versionStrategy: "Publication number, revision, publication date, and supersession metadata",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes:
      "Technical security baseline only when the contractual vehicle, clause version, or source-backed applicability facts establish the relevant revision.",
    currentVerifiedVersion: {
      versionIdentifier: "NIST SP 800-171 Revision 3",
      publicationDate: "2024-05-14",
      verifiedAt,
      provenanceUrl: "https://csrc.nist.gov/Pubs/sp/800/171/r3/final",
      supersedes: "NIST SP 800-171 Revision 2",
    },
  },
  {
    sourceId: "nist-sp-800-171a-r3",
    sourceFamily: "NIST",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "National Institute of Standards and Technology",
    canonicalTitle: "NIST SP 800-171A Revision 3 — Assessing CUI Security Requirements",
    canonicalUrl: "https://csrc.nist.gov/pubs/sp/800/171/a/r3/final",
    sourceType: "standard",
    updateCadence: "event-driven",
    versionStrategy: "Publication number, revision, publication date, and supersession metadata",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes: "Assessment procedures supporting source-backed cybersecurity evaluation; not itself proof that a particular subcontract requires a specific assessment.",
    currentVerifiedVersion: {
      versionIdentifier: "NIST SP 800-171A Revision 3",
      publicationDate: "2024-05-14",
      verifiedAt,
      provenanceUrl: "https://csrc.nist.gov/pubs/sp/800/171/a/r3/final",
      supersedes: "NIST SP 800-171A (2018)",
    },
  },
  {
    sourceId: "dfars-252-204-7012",
    sourceFamily: "DFARS",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "U.S. Department of Defense",
    canonicalTitle: "DFARS 252.204-7012 — Safeguarding Covered Defense Information and Cyber Incident Reporting",
    canonicalUrl: "https://www.acquisition.gov/dfars/252.204-7012-safeguarding-covered-defense-information-and-cyber-incident-reporting.",
    sourceType: "clause",
    updateCadence: "event-driven",
    versionStrategy: "Clause revision date plus governing DFARS change snapshot",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes: "Safeguarding, incident reporting, media preservation, cloud, and subcontract flowdown requirements when applicable.",
  },
  {
    sourceId: "dfars-252-204-7019",
    sourceFamily: "DFARS",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "U.S. Department of Defense",
    canonicalTitle: "DFARS 252.204-7019 — Notice of NIST SP 800-171 DoD Assessment Requirements",
    canonicalUrl: "https://www.acquisition.gov/dfars/part-252-solicitation-provisions-and-contract-clauses",
    sourceType: "clause",
    updateCadence: "event-driven",
    versionStrategy: "Clause revision date plus governing DFARS change snapshot",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes: "Solicitation assessment-status requirements; retrieve the exact clause unit from the versioned DFARS snapshot.",
  },
  {
    sourceId: "dfars-252-204-7020",
    sourceFamily: "DFARS",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "U.S. Department of Defense",
    canonicalTitle: "DFARS 252.204-7020 — NIST SP 800-171 DoD Assessment Requirements",
    canonicalUrl: "https://www.acquisition.gov/dfars/part-252-solicitation-provisions-and-contract-clauses",
    sourceType: "clause",
    updateCadence: "event-driven",
    versionStrategy: "Clause revision date plus governing DFARS change snapshot",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes: "Assessment access, SPRS, and subcontract requirements when applicable; retrieve the exact clause unit from the versioned DFARS snapshot.",
  },
  {
    sourceId: "dfars-252-204-7021",
    sourceFamily: "DFARS",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "U.S. Department of Defense",
    canonicalTitle: "DFARS 252.204-7021 — Contractor Compliance With CMMC Level Requirements",
    canonicalUrl: "https://www.acquisition.gov/dfars/252.204-7021-contractor-compliance-cybersecurity-maturity-model-certification-level-requirements.",
    sourceType: "clause",
    updateCadence: "event-driven",
    versionStrategy: "Clause revision date, CMMC phase, and governing DFARS change snapshot",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes:
      "CMMC level and flowdown requirements only when the solicitation or contract establishes the required level and phased applicability facts.",
  },
  {
    sourceId: "dfars-252-204-7025",
    sourceFamily: "DFARS",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "U.S. Department of Defense",
    canonicalTitle: "DFARS 252.204-7025 — Notice of CMMC Level Requirements",
    canonicalUrl: "https://www.acquisition.gov/dfars/252.204-7025-notice-cybersecurity-maturity-model-certification-level-requirements.",
    sourceType: "clause",
    updateCadence: "event-driven",
    versionStrategy: "Provision revision date, CMMC phase, and governing DFARS change snapshot",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes: "Solicitation notice identifying the CMMC level requirement; never infer an unstated level.",
  },
  {
    sourceId: "ecfr-32-part-170",
    sourceFamily: "CMMC",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "U.S. Department of Defense",
    canonicalTitle: "32 CFR Part 170 — Cybersecurity Maturity Model Certification Program",
    canonicalUrl: "https://www.ecfr.gov/current/title-32/subtitle-A/chapter-I/subchapter-D/part-170",
    sourceType: "program-rule",
    updateCadence: "daily",
    versionStrategy: "eCFR current-through date plus retained Federal Register provenance",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes: "CMMC program definitions, assessments, affirmations, status, and flowdown requirements.",
  },
  {
    sourceId: "dod-cmmc-program",
    sourceFamily: "CMMC",
    sourceTier: "official-guidance",
    jurisdiction: "federal",
    issuingAuthority: "U.S. Department of Defense",
    canonicalTitle: "Cybersecurity Maturity Model Certification Program Resources",
    canonicalUrl: "https://business.defense.gov/Programs/Cyber-Security-Resources/CMMC-20/",
    sourceType: "guidance",
    updateCadence: "weekly",
    versionStrategy: "Retrieved guidance snapshot with release and phase metadata",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes: "Official implementation guidance; controlling DFARS and 32 CFR text remains primary.",
  },
  {
    sourceId: "cui-registry",
    sourceFamily: "CUI Registry",
    sourceTier: "primary",
    jurisdiction: "federal",
    issuingAuthority: "National Archives and Records Administration",
    canonicalTitle: "Controlled Unclassified Information Registry",
    canonicalUrl: "https://www.archives.gov/cui",
    sourceType: "registry",
    updateCadence: "weekly",
    versionStrategy: "Retrieved registry snapshot with category and authority metadata",
    requiresHistoricalSnapshots: true,
    supportsClientCitation: true,
    applicabilityNotes: "Official source for CUI categories, authorities, markings, and safeguarding or dissemination controls.",
  },
] as const satisfies readonly RegulatorySourceCatalogEntry[];

export function getRegulatorySource(sourceId: string): RegulatorySourceCatalogEntry | undefined {
  return REGULATORY_SOURCE_CATALOG.find((source) => source.sourceId === sourceId);
}
